[project]
name = "qgpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flagembedding>=1.3.5",
    "loguru>=0.7.3",
    "numpy>=1.21.0",
    "pymilvus[model]>=2.3.0",
]
